<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      $cities= [
                ["name"=> "Kabul", "country_id"=> "1"],
                ["name"=> "Herat", "country_id"=> "1"],
                ["name"=> "Kandahar", "country_id"=> "1"],
                ["name"=> "Mazar-i-Sharif", "country_id"=> "1"],
                ["name"=> "Jalalabad", "country_id"=> "1"],
                ["name"=> "Kunduz", "country_id"=> "1"],
                ["name"=> "Ghazni", "country_id"=> "1"],
                ["name"=> "Balkh", "country_id"=> "1"],
                ["name"=> "Bamyan", "country_id"=> "1"],
                ["name"=> "Lashkar Gah", "country_id"=> "1"],
                ["name"=> "Tirana", "country_id"=> "2"],
                ["name"=> "Durrës", "country_id"=> "2"],
                ["name"=> "Vlorë", "country_id"=> "2"],
                ["name"=> "Shkodër", "country_id"=> "2"],
                ["name"=> "Elbasan", "country_id"=> "2"],
                ["name"=> "Korçë", "country_id"=> "2"],
                ["name"=> "Fier", "country_id"=> "2"],
                ["name"=> "Berat", "country_id"=> "2"],
                ["name"=> "Gjirokastër", "country_id"=> "2"],
                ["name"=> "Sarandë", "country_id"=> "2"],
                ["name"=> "Algiers", "country_id"=> "3"],
                ["name"=> "Oran", "country_id"=> "3"],
                ["name"=> "Constantine", "country_id"=> "3"],
                ["name"=> "Annaba", "country_id"=> "3"],
                ["name"=> "Blida", "country_id"=> "3"],
                ["name"=> "Batna", "country_id"=> "3"],
                ["name"=> "Sétif", "country_id"=> "3"],
                ["name"=> "Tlemcen", "country_id"=> "3"],
                ["name"=> "Béjaïa", "country_id"=> "3"],
                ["name"=> "Biskra", "country_id"=> "3"],
                ["name"=> "Andorra la Vella", "country_id"=> "4"],
                ["name"=> "Escaldes-Engordany", "country_id"=> "4"],
                ["name"=> "Encamp", "country_id"=> "4"],
                ["name"=> "Sant Julià de Lòria", "country_id"=> "4"],
                ["name"=> "La Massana", "country_id"=> "4"],
                ["name"=> "Ordino", "country_id"=> "4"],
                ["name"=> "Canillo", "country_id"=> "4"],
                ["name"=> "Pas de la Casa", "country_id"=> "4"],
                ["name"=> "Arinsal", "country_id"=> "4"],
                ["name"=> "El Tarter", "country_id"=> "4"],
                ["name"=> "Luanda", "country_id"=> "5"],
                ["name"=> "Huambo", "country_id"=> "5"],
                ["name"=> "Lobito", "country_id"=> "5"],
                ["name"=> "Benguela", "country_id"=> "5"],
                ["name"=> "Lubango", "country_id"=> "5"],
                ["name"=> "Kuito", "country_id"=> "5"],
                ["name"=> "Malanje", "country_id"=> "5"],
                ["name"=> "Namibe", "country_id"=> "5"],
                ["name"=> "Cabinda", "country_id"=> "5"],
                ["name"=> "Uíge", "country_id"=> "5"],
                ["name"=> "St. John's", "country_id"=> "6"],
                ["name"=> "All Saints", "country_id"=> "6"],
                ["name"=> "Liberta", "country_id"=> "6"],
                ["name"=> "Potter's Village", "country_id"=> "6"],
                ["name"=> "Bolans", "country_id"=> "6"],
                ["name"=> "Parham", "country_id"=> "6"],
                ["name"=> "Bolands", "country_id"=> "6"],
                ["name"=> "Codrington", "country_id"=> "6"],
                ["name"=> "Old Road", "country_id"=> "6"],
                ["name"=> "English Harbour", "country_id"=> "6"],
                ["name"=> "Buenos Aires", "country_id"=> "7"],
                ["name"=> "Córdoba", "country_id"=> "7"],
                ["name"=> "Rosario", "country_id"=> "7"],
                ["name"=> "Mendoza", "country_id"=> "7"],
                ["name"=> "La Plata", "country_id"=> "7"],
                ["name"=> "San Miguel de Tucumán", "country_id"=> "7"],
                ["name"=> "Mar del Plata", "country_id"=> "7"],
                ["name"=> "Salta", "country_id"=> "7"],
                ["name"=> "Santa Fe", "country_id"=> "7"],
                ["name"=> "San Juan", "country_id"=> "7"],
                ["name"=> "Yerevan", "country_id"=> "8"],
                ["name"=> "Gyumri", "country_id"=> "8"],
                ["name"=> "Vanadzor", "country_id"=> "8"],
                ["name"=> "Vagharshapat", "country_id"=> "8"],
                ["name"=> "Hrazdan", "country_id"=> "8"],
                ["name"=> "Abovyan", "country_id"=> "8"],
                ["name"=> "Kapan", "country_id"=> "8"],
                ["name"=> "Armavir", "country_id"=> "8"],
                ["name"=> "Gavar", "country_id"=> "8"],
                ["name"=> "Artashat", "country_id"=> "8"],
                ["name"=> "Sydney", "country_id"=> "9"],
                ["name"=> "Melbourne", "country_id"=> "9"],
                ["name"=> "Brisbane", "country_id"=> "9"],
                ["name"=> "Perth", "country_id"=> "9"],
                ["name"=> "Adelaide", "country_id"=> "9"],
                ["name"=> "Gold Coast", "country_id"=> "9"],
                ["name"=> "Canberra", "country_id"=> "9"],
                ["name"=> "Newcastle", "country_id"=> "9"],
                ["name"=> "Wollongong", "country_id"=> "9"],
                ["name"=> "Hobart", "country_id"=> "9"],
                ["name"=> "Vienna", "country_id"=> "10"],
                ["name"=> "Graz", "country_id"=> "10"],
                ["name"=> "Linz", "country_id"=> "10"],
                ["name"=> "Salzburg", "country_id"=> "10"],
                ["name"=> "Innsbruck", "country_id"=> "10"],
                ["name"=> "Klagenfurt", "country_id"=> "10"],
                ["name"=> "Villach", "country_id"=> "10"],
                ["name"=> "Wels", "country_id"=> "10"],
                ["name"=> "Sankt Pölten", "country_id"=> "10"],
                ["name"=> "Dornbirn", "country_id"=> "10"],
                ["name"=> "Baku", "country_id"=> "11"],
                ["name"=> "Ganja", "country_id"=> "11"],
                ["name"=> "Sumqayit", "country_id"=> "11"],
                ["name"=> "Lankaran", "country_id"=> "11"],
                ["name"=> "Mingachevir", "country_id"=> "11"],
                ["name"=> "Shirvan", "country_id"=> "11"],
                ["name"=> "Nakhchivan", "country_id"=> "11"],
                ["name"=> "Shaki", "country_id"=> "11"],
                ["name"=> "Yevlakh", "country_id"=> "11"],
                ["name"=> "Khankendi", "country_id"=> "11"],
                ["name"=> "Nassau", "country_id"=> "12"],
                ["name"=> "Freeport", "country_id"=> "12"],
                ["name"=> "West End", "country_id"=> "12"],
                ["name"=> "Cooper's Town", "country_id"=> "12"],
                ["name"=> "Marsh Harbour", "country_id"=> "12"],
                ["name"=> "Lucaya", "country_id"=> "12"],
                ["name"=> "George Town", "country_id"=> "12"],
                ["name"=> "Alice Town", "country_id"=> "12"],
                ["name"=> "Spanish Wells", "country_id"=> "12"],
                ["name"=> "Matthew Town", "country_id"=> "12"],
                ["name"=> "Manama", "country_id"=> "13"],
                ["name"=> "Muharraq", "country_id"=> "13"],
                ["name"=> "Riffa", "country_id"=> "13"],
                ["name"=> "Hamad Town", "country_id"=> "13"],
                ["name"=> "A'ali", "country_id"=> "13"],
                ["name"=> "Isa Town", "country_id"=> "13"],
                ["name"=> "Sitra", "country_id"=> "13"],
                ["name"=> "Budaiya", "country_id"=> "13"],
                ["name"=> "Jidhafs", "country_id"=> "13"],
                ["name"=> "Al-Manamah", "country_id"=> "13"],
                ["name"=> "Dhaka", "country_id"=> "14"],
                ["name"=> "Chittagong", "country_id"=> "14"],
                ["name"=> "Khulna", "country_id"=> "14"],
                ["name"=> "Rajshahi", "country_id"=> "14"],
                ["name"=> "Sylhet", "country_id"=> "14"],
                ["name"=> "Barisal", "country_id"=> "14"],
                ["name"=> "Rangpur", "country_id"=> "14"],
                ["name"=> "Comilla", "country_id"=> "14"],
                ["name"=> "Narayanganj", "country_id"=> "14"],
                ["name"=> "Mymensingh", "country_id"=> "14"],
                ["name"=> "Bridgetown", "country_id"=> "15"],
                ["name"=> "Speightstown", "country_id"=> "15"],
                ["name"=> "Oistins", "country_id"=> "15"],
                ["name"=> "Bathsheba", "country_id"=> "15"],
                ["name"=> "Holetown", "country_id"=> "15"],
                ["name"=> "Crane", "country_id"=> "15"],
                ["name"=> "Six Cross Roads", "country_id"=> "15"],
                ["name"=> "The Garden", "country_id"=> "15"],
                ["name"=> "Welchman Hall", "country_id"=> "15"],
                ["name"=> "Paynes Bay", "country_id"=> "15"],
                ["name"=> "Minsk", "country_id"=> "16"],
                ["name"=> "Gomel", "country_id"=> "16"],
                ["name"=> "Mogilev", "country_id"=> "16"],
                ["name"=> "Vitebsk", "country_id"=> "16"],
                ["name"=> "Grodno", "country_id"=> "16"],
                ["name"=> "Brest", "country_id"=> "16"],
                ["name"=> "Bobruisk", "country_id"=> "16"],
                ["name"=> "Baranovichi", "country_id"=> "16"],
                ["name"=> "Borisov", "country_id"=> "16"],
                ["name"=> "Pinsk", "country_id"=> "16"],
                ["name"=> "Brussels", "country_id"=> "17"],
                ["name"=> "Antwerp", "country_id"=> "17"],
                ["name"=> "Ghent", "country_id"=> "17"],
                ["name"=> "Charleroi", "country_id"=> "17"],
                ["name"=> "Liège", "country_id"=> "17"],
                ["name"=> "Bruges", "country_id"=> "17"],
                ["name"=> "Namur", "country_id"=> "17"],
                ["name"=> "Leuven", "country_id"=> "17"],
                ["name"=> "Mons", "country_id"=> "17"],
                ["name"=> "Mechelen", "country_id"=> "17"],
                ["name"=> "Belize City", "country_id"=> "18"],
                ["name"=> "San Ignacio", "country_id"=> "18"],
                ["name"=> "Orange Walk", "country_id"=> "18"],
                ["name"=> "Belmopan", "country_id"=> "18"],
                ["name"=> "Dangriga", "country_id"=> "18"],
                ["name"=> "Corozal", "country_id"=> "18"],
                ["name"=> "San Pedro", "country_id"=> "18"],
                ["name"=> "Benque Viejo del Carmen", "country_id"=> "18"],
                ["name"=> "Punta Gorda", "country_id"=> "18"],
                ["name"=> "Hopkins", "country_id"=> "18"],
                ["name"=> "Porto-Novo", "country_id"=> "19"],
                ["name"=> "Cotonou", "country_id"=> "19"],
                ["name"=> "Parakou", "country_id"=> "19"],
                ["name"=> "Djougou", "country_id"=> "19"],
                ["name"=> "Bohicon", "country_id"=> "19"],
                ["name"=> "Kandi", "country_id"=> "19"],
                ["name"=> "Abomey", "country_id"=> "19"],
                ["name"=> "Natitingou", "country_id"=> "19"],
                ["name"=> "Lokossa", "country_id"=> "19"],
                ["name"=> "Ouidah", "country_id"=> "19"],
                ["name"=> "Thimphu", "country_id"=> "20"],
                ["name"=> "Phuntsholing", "country_id"=> "20"],
                ["name"=> "Paro", "country_id"=> "20"],
                ["name"=> "Punakha", "country_id"=> "20"],
                ["name"=> "Wangdue Phodrang", "country_id"=> "20"],
                ["name"=> "Jakar", "country_id"=> "20"],
                ["name"=> "Samdrup Jongkhar", "country_id"=> "20"],
                ["name"=> "Gelephu", "country_id"=> "20"],
                ["name"=> "Trongsa", "country_id"=> "20"],
                ["name"=> "Mongar", "country_id"=> "20"],
                ["name"=> "La Paz", "country_id"=> "21"],
                ["name"=> "Santa Cruz de la Sierra", "country_id"=> "21"],
                ["name"=> "Cochabamba", "country_id"=> "21"],
                ["name"=> "Sucre", "country_id"=> "21"],
                ["name"=> "Oruro", "country_id"=> "21"],
                ["name"=> "Tarija", "country_id"=> "21"],
                ["name"=> "Potosí", "country_id"=> "21"],
                ["name"=> "Trinidad", "country_id"=> "21"],
                ["name"=> "Cobija", "country_id"=> "21"],
                ["name"=> "Riberalta", "country_id"=> "21"],
                ["name"=> "Sarajevo", "country_id"=> "22"],
                ["name"=> "Banja Luka", "country_id"=> "22"],
                ["name"=> "Tuzla", "country_id"=> "22"],
                ["name"=> "Zenica", "country_id"=> "22"],
                ["name"=> "Mostar", "country_id"=> "22"],
                ["name"=> "Bihać", "country_id"=> "22"],
                ["name"=> "Prijedor", "country_id"=> "22"],
                ["name"=> "Trebinje", "country_id"=> "22"],
                ["name"=> "Travnik", "country_id"=> "22"],
                ["name"=> "Doboj", "country_id"=> "22"],
                ["name"=> "Gaborone", "country_id"=> "23"],
                ["name"=> "Francistown", "country_id"=> "23"],
                ["name"=> "Molepolole", "country_id"=> "23"],
                ["name"=> "Maun", "country_id"=> "23"],
                ["name"=> "Serowe", "country_id"=> "23"],
                ["name"=> "Selibe Phikwe", "country_id"=> "23"],
                ["name"=> "Kanye", "country_id"=> "23"],
                ["name"=> "Mochudi", "country_id"=> "23"],
                ["name"=> "Mahalapye", "country_id"=> "23"],
                ["name"=> "Palapye", "country_id"=> "23"],
                ["name"=> "São Paulo", "country_id"=> "24"],
                ["name"=> "Rio de Janeiro", "country_id"=> "24"],
                ["name"=> "Brasília", "country_id"=> "24"],
                ["name"=> "Salvador", "country_id"=> "24"],
                ["name"=> "Fortaleza", "country_id"=> "24"],
                ["name"=> "Belo Horizonte", "country_id"=> "24"],
                ["name"=> "Manaus", "country_id"=> "24"],
                ["name"=> "Curitiba", "country_id"=> "24"],
                ["name"=> "Recife", "country_id"=> "24"],
                ["name"=> "Porto Alegre", "country_id"=> "24"],
                ["name"=> "Bandar Seri Begawan", "country_id"=> "25"],
                ["name"=> "Kuala Belait", "country_id"=> "25"],
                ["name"=> "Seria", "country_id"=> "25"],
                ["name"=> "Tutong", "country_id"=> "25"],
                ["name"=> "Bangar", "country_id"=> "25"],
                ["name"=> "Jerudong", "country_id"=> "25"],
                ["name"=> "Lumapas", "country_id"=> "25"],
                ["name"=> "Bukit Sawat", "country_id"=> "25"],
                ["name"=> "Muara", "country_id"=> "25"],
                ["name"=> "Mentiri", "country_id"=> "25"],
                ["name"=> "Sofia", "country_id"=> "26"],
                ["name"=> "Plovdiv", "country_id"=> "26"],
                ["name"=> "Varna", "country_id"=> "26"],
                ["name"=> "Burgas", "country_id"=> "26"],
                ["name"=> "Ruse", "country_id"=> "26"],
                ["name"=> "Stara Zagora", "country_id"=> "26"],
                ["name"=> "Pleven", "country_id"=> "26"],
                ["name"=> "Sliven", "country_id"=> "26"],
                ["name"=> "Dobrich", "country_id"=> "26"],
                ["name"=> "Shumen", "country_id"=> "26"],
                ["name"=> "Ouagadougou", "country_id"=> "27"],
                ["name"=> "Bobo-Dioulasso", "country_id"=> "27"],
                ["name"=> "Koudougou", "country_id"=> "27"],
                ["name"=> "Ouahigouya", "country_id"=> "27"],
                ["name"=> "Banfora", "country_id"=> "27"],
                ["name"=> "Dédougou", "country_id"=> "27"],
                ["name"=> "Kaya", "country_id"=> "27"],
                ["name"=> "Tenkodogo", "country_id"=> "27"],
                ["name"=> "Fada N'gourma", "country_id"=> "27"],
                ["name"=> "Houndé", "country_id"=> "27"],
                ["name"=> "Bujumbura", "country_id"=> "28"],
                ["name"=> "Gitega", "country_id"=> "28"],
                ["name"=> "Muyinga", "country_id"=> "28"],
                ["name"=> "Ngozi", "country_id"=> "28"],
                ["name"=> "Ruyigi", "country_id"=> "28"],
                ["name"=> "Kayanza", "country_id"=> "28"],
                ["name"=> "Bururi", "country_id"=> "28"],
                ["name"=> "Makamba", "country_id"=> "28"],
                ["name"=> "Rumonge", "country_id"=> "28"],
                ["name"=> "Muramvya", "country_id"=> "28"],
                ["name"=> "Praia", "country_id"=> "29"],
                ["name"=> "Mindelo", "country_id"=> "29"],
                ["name"=> "Santa Maria", "country_id"=> "29"],
                ["name"=> "Assomada", "country_id"=> "29"],
                ["name"=> "Pedra Badejo", "country_id"=> "29"],
                ["name"=> "São Filipe", "country_id"=> "29"],
                ["name"=> "Tarrafal", "country_id"=> "29"],
                ["name"=> "Espargos", "country_id"=> "29"],
                ["name"=> "Porto Novo", "country_id"=> "29"],
                ["name"=> "Ribeira Grande", "country_id"=> "29"],
                ["name"=> "Phnom Penh", "country_id"=> "30"],
                ["name"=> "Siem Reap", "country_id"=> "30"],
                ["name"=> "Battambang", "country_id"=> "30"],
                ["name"=> "Sihanoukville", "country_id"=> "30"],
                ["name"=> "Poipet", "country_id"=> "30"],
                ["name"=> "Kampong Cham", "country_id"=> "30"],
                ["name"=> "Pursat", "country_id"=> "30"],
                ["name"=> "Kampot", "country_id"=> "30"],
                ["name"=> "Koh Kong", "country_id"=> "30"],
                ["name"=> "Prey Veng", "country_id"=> "30"],
                ["name"=> "Yaoundé", "country_id"=> "31"],
                ["name"=> "Douala", "country_id"=> "31"],
                ["name"=> "Garoua", "country_id"=> "31"],
                ["name"=> "Bamenda", "country_id"=> "31"],
                ["name"=> "Maroua", "country_id"=> "31"],
                ["name"=> "Bafoussam", "country_id"=> "31"],
                ["name"=> "Ngaoundéré", "country_id"=> "31"],
                ["name"=> "Bertoua", "country_id"=> "31"],
                ["name"=> "Kumba", "country_id"=> "31"],
                ["name"=> "Nkongsamba", "country_id"=> "31"],
                ["name"=> "Toronto", "country_id"=> "32"],
                ["name"=> "Montreal", "country_id"=> "32"],
                ["name"=> "Vancouver", "country_id"=> "32"],
                ["name"=> "Calgary", "country_id"=> "32"],
                ["name"=> "Edmonton", "country_id"=> "32"],
                ["name"=> "Ottawa", "country_id"=> "32"],
                ["name"=> "Winnipeg", "country_id"=> "32"],
                ["name"=> "Quebec City", "country_id"=> "32"],
                ["name"=> "Hamilton", "country_id"=> "32"],
                ["name"=> "Halifax", "country_id"=> "32"],
                ["name"=> "Bangui", "country_id"=> "33"],
                ["name"=> "Bimbo", "country_id"=> "33"],
                ["name"=> "Berbérati", "country_id"=> "33"],
                ["name"=> "Carnot", "country_id"=> "33"],
                ["name"=> "Bambari", "country_id"=> "33"],
                ["name"=> "Bouar", "country_id"=> "33"],
                ["name"=> "Bossangoa", "country_id"=> "33"],
                ["name"=> "Bria", "country_id"=> "33"],
                ["name"=> "Bangassou", "country_id"=> "33"],
                ["name"=> "Nola", "country_id"=> "33"],
                ["name"=> "N'Djamena", "country_id"=> "34"],
                ["name"=> "Moundou", "country_id"=> "34"],
                ["name"=> "Sarh", "country_id"=> "34"],
                ["name"=> "Abéché", "country_id"=> "34"],
                ["name"=> "Kelo", "country_id"=> "34"],
                ["name"=> "Koumra", "country_id"=> "34"],
                ["name"=> "Pala", "country_id"=> "34"],
                ["name"=> "Am Timan", "country_id"=> "34"],
                ["name"=> "Bongor", "country_id"=> "34"],
                ["name"=> "Mongo", "country_id"=> "34"],
                ["name"=> "Santiago", "country_id"=> "35"],
                ["name"=> "Valparaíso", "country_id"=> "35"],
                ["name"=> "Concepción", "country_id"=> "35"],
                ["name"=> "La Serena", "country_id"=> "35"],
                ["name"=> "Antofagasta", "country_id"=> "35"],
                ["name"=> "Temuco", "country_id"=> "35"],
                ["name"=> "Rancagua", "country_id"=> "35"],
                ["name"=> "Talca", "country_id"=> "35"],
                ["name"=> "Arica", "country_id"=> "35"],
                ["name"=> "Puerto Montt", "country_id"=> "35"],
                ["name"=> "Beijing", "country_id"=> "36"],
                ["name"=> "Shanghai", "country_id"=> "36"],
                ["name"=> "Guangzhou", "country_id"=> "36"],
                ["name"=> "Shenzhen", "country_id"=> "36"],
                ["name"=> "Chengdu", "country_id"=> "36"],
                ["name"=> "Tianjin", "country_id"=> "36"],
                ["name"=> "Chongqing", "country_id"=> "36"],
                ["name"=> "Wuhan", "country_id"=> "36"],
                ["name"=> "Xi'an", "country_id"=> "36"],
                ["name"=> "Hangzhou", "country_id"=> "36"],
                ["name"=> "Bogotá", "country_id"=> "37"],
                ["name"=> "Medellín", "country_id"=> "37"],
                ["name"=> "Cali", "country_id"=> "37"],
                ["name"=> "Barranquilla", "country_id"=> "37"],
                ["name"=> "Cartagena", "country_id"=> "37"],
                ["name"=> "Cúcuta", "country_id"=> "37"],
                ["name"=> "Bucaramanga", "country_id"=> "37"],
                ["name"=> "Pereira", "country_id"=> "37"],
                ["name"=> "Santa Marta", "country_id"=> "37"],
                ["name"=> "Ibagué", "country_id"=> "37"],
                ["name"=> "Moroni", "country_id"=> "38"],
                ["name"=> "Mutsamudu", "country_id"=> "38"],
                ["name"=> "Fomboni", "country_id"=> "38"],
                ["name"=> "Domoni", "country_id"=> "38"],
                ["name"=> "Mitsamiouli", "country_id"=> "38"],
                ["name"=> "Tsimbeo", "country_id"=> "38"],
                ["name"=> "Ouani", "country_id"=> "38"],
                ["name"=> "Adda-Douéni", "country_id"=> "38"],
                ["name"=> "Sima", "country_id"=> "38"],
                ["name"=> "Mbéni", "country_id"=> "38"],
                ["name"=> "Brazzaville", "country_id"=> "39"],
                ["name"=> "Pointe-Noire", "country_id"=> "39"],
                ["name"=> "Dolisie", "country_id"=> "39"],
                ["name"=> "Nkayi", "country_id"=> "39"],
                ["name"=> "Owando", "country_id"=> "39"],
                ["name"=> "Ouesso", "country_id"=> "39"],
                ["name"=> "Impfondo", "country_id"=> "39"],
                ["name"=> "Sibiti", "country_id"=> "39"],
                ["name"=> "Mossendjo", "country_id"=> "39"],
                ["name"=> "Madingou", "country_id"=> "39"],
                ["name"=> "Kinshasa", "country_id"=> "40"],
                ["name"=> "Lubumbashi", "country_id"=> "40"],
                ["name"=> "Mbuji-Mayi", "country_id"=> "40"],
                ["name"=> "Kananga", "country_id"=> "40"],
                ["name"=> "Kisangani", "country_id"=> "40"],
                ["name"=> "Bukavu", "country_id"=> "40"],
                ["name"=> "Goma", "country_id"=> "40"],
                ["name"=> "Kolwezi", "country_id"=> "40"],
                ["name"=> "Likasi", "country_id"=> "40"],
                ["name"=> "Matadi", "country_id"=> "40"],
                ["name"=> "San José", "country_id"=> "41"],
                ["name"=> "Limón", "country_id"=> "41"],
                ["name"=> "Alajuela", "country_id"=> "41"],
                ["name"=> "Heredia", "country_id"=> "41"],
                ["name"=> "Puntarenas", "country_id"=> "41"],
                ["name"=> "Cartago", "country_id"=> "41"],
                ["name"=> "Liberia", "country_id"=> "41"],
                ["name"=> "Paraíso", "country_id"=> "41"],
                ["name"=> "Curridabat", "country_id"=> "41"],
                ["name"=> "San Isidro", "country_id"=> "41"],
                ["name"=> "Zagreb", "country_id"=> "42"],
                ["name"=> "Split", "country_id"=> "42"],
                ["name"=> "Rijeka", "country_id"=> "42"],
                ["name"=> "Osijek", "country_id"=> "42"],
                ["name"=> "Zadar", "country_id"=> "42"],
                ["name"=> "Pula", "country_id"=> "42"],
                ["name"=> "Slavonski Brod", "country_id"=> "42"],
                ["name"=> "Karlovac", "country_id"=> "42"],
                ["name"=> "Varaždin", "country_id"=> "42"],
                ["name"=> "Dubrovnik", "country_id"=> "42"],
                ["name"=> "Havana", "country_id"=> "43"],
                ["name"=> "Santiago de Cuba", "country_id"=> "43"],
                ["name"=> "Camagüey", "country_id"=> "43"],
                ["name"=> "Holguín", "country_id"=> "43"],
                ["name"=> "Santa Clara", "country_id"=> "43"],
                ["name"=> "Guantánamo", "country_id"=> "43"],
                ["name"=> "Bayamo", "country_id"=> "43"],
                ["name"=> "Las Tunas", "country_id"=> "43"],
                ["name"=> "Cienfuegos", "country_id"=> "43"],
                ["name"=> "Pinar del Río", "country_id"=> "43"],
                ["name"=> "Nicosia", "country_id"=> "44"],
                ["name"=> "Limassol", "country_id"=> "44"],
                ["name"=> "Larnaca", "country_id"=> "44"],
                ["name"=> "Paphos", "country_id"=> "44"],
                ["name"=> "Famagusta", "country_id"=> "44"],
                ["name"=> "Kyrenia", "country_id"=> "44"],
                ["name"=> "Protaras", "country_id"=> "44"],
                ["name"=> "Paralimni", "country_id"=> "44"],
                ["name"=> "Morphou", "country_id"=> "44"],
                ["name"=> "Polis", "country_id"=> "44"],
                ["name"=> "Prague", "country_id"=> "45"],
                ["name"=> "Brno", "country_id"=> "45"],
                ["name"=> "Ostrava", "country_id"=> "45"],
                ["name"=> "Plzeň", "country_id"=> "45"],
                ["name"=> "Liberec", "country_id"=> "45"],
                ["name"=> "Olomouc", "country_id"=> "45"],
                ["name"=> "České Budějovice", "country_id"=> "45"],
                ["name"=> "Hradec Králové", "country_id"=> "45"],
                ["name"=> "Ústí nad Labem", "country_id"=> "45"],
                ["name"=> "Pardubice", "country_id"=> "45"],
                ["name"=> "Copenhagen", "country_id"=> "46"],
                ["name"=> "Aarhus", "country_id"=> "46"],
                ["name"=> "Odense", "country_id"=> "46"],
                ["name"=> "Aalborg", "country_id"=> "46"],
                ["name"=> "Esbjerg", "country_id"=> "46"],
                ["name"=> "Randers", "country_id"=> "46"],
                ["name"=> "Kolding", "country_id"=> "46"],
                ["name"=> "Horsens", "country_id"=> "46"],
                ["name"=> "Vejle", "country_id"=> "46"],
                ["name"=> "Roskilde", "country_id"=> "46"],
                ["name"=> "Djibouti City", "country_id"=> "47"],
                ["name"=> "Ali Sabieh", "country_id"=> "47"],
                ["name"=> "Tadjoura", "country_id"=> "47"],
                ["name"=> "Obock", "country_id"=> "47"],
                ["name"=> "Dikhil", "country_id"=> "47"],
                ["name"=> "Arta", "country_id"=> "47"],
                ["name"=> "Holhol", "country_id"=> "47"],
                ["name"=> "Galafi", "country_id"=> "47"],
                ["name"=> "Yoboki", "country_id"=> "47"],
                ["name"=> "Randa", "country_id"=> "47"],
                ["name"=> "Roseau", "country_id"=> "48"],
                ["name"=> "Portsmouth", "country_id"=> "48"],
                ["name"=> "Marigot", "country_id"=> "48"],
                ["name"=> "Berekua", "country_id"=> "48"],
                ["name"=> "Saint Joseph", "country_id"=> "48"],
                ["name"=> "Wesley", "country_id"=> "48"],
                ["name"=> "Mahaut", "country_id"=> "48"],
                ["name"=> "Canefield", "country_id"=> "48"],
                ["name"=> "Soufrière", "country_id"=> "48"],
                ["name"=> "Calibishie", "country_id"=> "48"],
                ["name"=> "Santo Domingo", "country_id"=> "49"],
                ["name"=> "Santiago de los Caballeros", "country_id"=> "49"],
                ["name"=> "La Romana", "country_id"=> "49"],
                ["name"=> "San Pedro de Macorís", "country_id"=> "49"],
                ["name"=> "San Cristóbal", "country_id"=> "49"],
                ["name"=> "Puerto Plata", "country_id"=> "49"],
                ["name"=> "La Vega", "country_id"=> "49"],
                ["name"=> "Higüey", "country_id"=> "49"],
                ["name"=> "Boca Chica", "country_id"=> "49"],
                ["name"=> "San Francisco de Macorís", "country_id"=> "49"],
                ["name"=> "Quito", "country_id"=> "50"],
                ["name"=> "Guayaquil", "country_id"=> "50"],
                ["name"=> "Cuenca", "country_id"=> "50"],
                ["name"=> "Santo Domingo", "country_id"=> "50"],
                ["name"=> "Machala", "country_id"=> "50"],
                ["name"=> "Manta", "country_id"=> "50"],
                ["name"=> "Portoviejo", "country_id"=> "50"],
                ["name"=> "Loja", "country_id"=> "50"],
                ["name"=> "Ambato", "country_id"=> "50"],
                ["name"=> "Riobamba", "country_id"=> "50"],
                ["name"=> "Cairo", "country_id"=> "51"],
                ["name"=> "Alexandria", "country_id"=> "51"],
                ["name"=> "Giza", "country_id"=> "51"],
                ["name"=> "Shubra El-Kheima", "country_id"=> "51"],
                ["name"=> "Port Said", "country_id"=> "51"],
                ["name"=> "Suez", "country_id"=> "51"],
                ["name"=> "Luxor", "country_id"=> "51"],
                ["name"=> "Aswan", "country_id"=> "51"],
                ["name"=> "Mansoura", "country_id"=> "51"],
                ["name"=> "Tanta", "country_id"=> "51"],
                ["name"=> "San Salvador", "country_id"=> "52"],
                ["name"=> "Santa Ana", "country_id"=> "52"],
                ["name"=> "San Miguel", "country_id"=> "52"],
                ["name"=> "Soyapango", "country_id"=> "52"],
                ["name"=> "Mejicanos", "country_id"=> "52"],
                ["name"=> "Santa Tecla", "country_id"=> "52"],
                ["name"=> "Apopa", "country_id"=> "52"],
                ["name"=> "Delgado", "country_id"=> "52"],
                ["name"=> "Ilopango", "country_id"=> "52"],
                ["name"=> "Usulután", "country_id"=> "52"],
                ["name"=> "Malabo", "country_id"=> "53"],
                ["name"=> "Bata", "country_id"=> "53"],
                ["name"=> "Ebebiyin", "country_id"=> "53"],
                ["name"=> "Aconibe", "country_id"=> "53"],
                ["name"=> "Añisoc", "country_id"=> "53"],
                ["name"=> "Luba", "country_id"=> "53"],
                ["name"=> "Evinayong", "country_id"=> "53"],
                ["name"=> "Mongomo", "country_id"=> "53"],
                ["name"=> "Nsok", "country_id"=> "53"],
                ["name"=> "Rebola", "country_id"=> "53"],
                ["name"=> "Asmara", "country_id"=> "54"],
                ["name"=> "Keren", "country_id"=> "54"],
                ["name"=> "Massawa", "country_id"=> "54"],
                ["name"=> "Assab", "country_id"=> "54"],
                ["name"=> "Mendefera", "country_id"=> "54"],
                ["name"=> "Barentu", "country_id"=> "54"],
                ["name"=> "Adi Keyh", "country_id"=> "54"],
                ["name"=> "Dekemhare", "country_id"=> "54"],
                ["name"=> "Edd", "country_id"=> "54"],
                ["name"=> "Teseney", "country_id"=> "54"],
                ["name"=> "Tallinn", "country_id"=> "55"],
                ["name"=> "Tartu", "country_id"=> "55"],
                ["name"=> "Narva", "country_id"=> "55"],
                ["name"=> "Pärnu", "country_id"=> "55"],
                ["name"=> "Kohtla-Järve", "country_id"=> "55"],
                ["name"=> "Viljandi", "country_id"=> "55"],
                ["name"=> "Rakvere", "country_id"=> "55"],
                ["name"=> "Maardu", "country_id"=> "55"],
                ["name"=> "Sillamäe", "country_id"=> "55"],
                ["name"=> "Kuressaare", "country_id"=> "55"],
                ["name"=> "Mbabane", "country_id"=> "56"],
                ["name"=> "Manzini", "country_id"=> "56"],
                ["name"=> "Lobamba", "country_id"=> "56"],
                ["name"=> "Big Bend", "country_id"=> "56"],
                ["name"=> "Siteki", "country_id"=> "56"],
                ["name"=> "Piggs Peak", "country_id"=> "56"],
                ["name"=> "Nhlangano", "country_id"=> "56"],
                ["name"=> "Malkerns", "country_id"=> "56"],
                ["name"=> "Hluti", "country_id"=> "56"],
                ["name"=> "Kwaluseni", "country_id"=> "56"],
                ["name"=> "Addis Ababa", "country_id"=> "57"],
                ["name"=> "Dire Dawa", "country_id"=> "57"],
                ["name"=> "Mekelle", "country_id"=> "57"],
                ["name"=> "Gondar", "country_id"=> "57"],
                ["name"=> "Bahir Dar", "country_id"=> "57"],
                ["name"=> "Hawassa", "country_id"=> "57"],
                ["name"=> "Adama", "country_id"=> "57"],
                ["name"=> "Jimma", "country_id"=> "57"],
                ["name"=> "Dessie", "country_id"=> "57"],
                ["name"=> "Harar", "country_id"=> "57"],
                ["name"=> "Suva", "country_id"=> "58"],
                ["name"=> "Nadi", "country_id"=> "58"],
                ["name"=> "Lautoka", "country_id"=> "58"],
                ["name"=> "Labasa", "country_id"=> "58"],
                ["name"=> "Ba", "country_id"=> "58"],
                ["name"=> "Sigatoka", "country_id"=> "58"],
                ["name"=> "Rakiraki", "country_id"=> "58"],
                ["name"=> "Tavua", "country_id"=> "58"],
                ["name"=> "Savusavu", "country_id"=> "58"],
                ["name"=> "Levuka", "country_id"=> "58"],
                ["name"=> "Helsinki", "country_id"=> "59"],
                ["name"=> "Espoo", "country_id"=> "59"],
                ["name"=> "Tampere", "country_id"=> "59"],
                ["name"=> "Vantaa", "country_id"=> "59"],
                ["name"=> "Oulu", "country_id"=> "59"],
                ["name"=> "Turku", "country_id"=> "59"],
                ["name"=> "Jyväskylä", "country_id"=> "59"],
                ["name"=> "Lahti", "country_id"=> "59"],
                ["name"=> "Kuopio", "country_id"=> "59"],
                ["name"=> "Pori", "country_id"=> "59"],
                ["name"=> "Paris", "country_id"=> "60"],
                ["name"=> "Marseille", "country_id"=> "60"],
                ["name"=> "Lyon", "country_id"=> "60"],
                ["name"=> "Toulouse", "country_id"=> "60"],
                ["name"=> "Nice", "country_id"=> "60"],
                ["name"=> "Nantes", "country_id"=> "60"],
                ["name"=> "Strasbourg", "country_id"=> "60"],
                ["name"=> "Montpellier", "country_id"=> "60"],
                ["name"=> "Bordeaux", "country_id"=> "60"],
                ["name"=> "Lille", "country_id"=> "60"],
                ["name"=> "Libreville", "country_id"=> "61"],
                ["name"=> "Port-Gentil", "country_id"=> "61"],
                ["name"=> "Franceville", "country_id"=> "61"],
                ["name"=> "Oyem", "country_id"=> "61"],
                ["name"=> "Moanda", "country_id"=> "61"],
                ["name"=> "Mouila", "country_id"=> "61"],
                ["name"=> "Lambaréné", "country_id"=> "61"],
                ["name"=> "Tchibanga", "country_id"=> "61"],
                ["name"=> "Koulamoutou", "country_id"=> "61"],
                ["name"=> "Makokou", "country_id"=> "61"],
                ["name"=> "Banjul", "country_id"=> "62"],
                ["name"=> "Serekunda", "country_id"=> "62"],
                ["name"=> "Brikama", "country_id"=> "62"],
                ["name"=> "Bakau", "country_id"=> "62"],
                ["name"=> "Farafenni", "country_id"=> "62"],
                ["name"=> "Lamin", "country_id"=> "62"],
                ["name"=> "Sukuta", "country_id"=> "62"],
                ["name"=> "Basse Santa Su", "country_id"=> "62"],
                ["name"=> "Gunjur", "country_id"=> "62"],
                ["name"=> "Kerewan", "country_id"=> "62"],
                ["name"=> "Tbilisi", "country_id"=> "63"],
                ["name"=> "Batumi", "country_id"=> "63"],
                ["name"=> "Kutaisi", "country_id"=> "63"],
                ["name"=> "Rustavi", "country_id"=> "63"],
                ["name"=> "Zugdidi", "country_id"=> "63"],
                ["name"=> "Gori", "country_id"=> "63"],
                ["name"=> "Poti", "country_id"=> "63"],
                ["name"=> "Kobuleti", "country_id"=> "63"],
                ["name"=> "Khashuri", "country_id"=> "63"],
                ["name"=> "Samtredia", "country_id"=> "63"],
                ["name"=> "Berlin", "country_id"=> "64"],
                ["name"=> "Hamburg", "country_id"=> "64"],
                ["name"=> "Munich", "country_id"=> "64"],
                ["name"=> "Cologne", "country_id"=> "64"],
                ["name"=> "Frankfurt", "country_id"=> "64"],
                ["name"=> "Stuttgart", "country_id"=> "64"],
                ["name"=> "Düsseldorf", "country_id"=> "64"],
                ["name"=> "Dortmund", "country_id"=> "64"],
                ["name"=> "Essen", "country_id"=> "64"],
                ["name"=> "Leipzig", "country_id"=> "64"],
                ["name"=> "Accra", "country_id"=> "65"],
                ["name"=> "Kumasi", "country_id"=> "65"],
                ["name"=> "Tamale", "country_id"=> "65"],
                ["name"=> "Sekondi-Takoradi", "country_id"=> "65"],
                ["name"=> "Ashaiman", "country_id"=> "65"],
                ["name"=> "Sunyani", "country_id"=> "65"],
                ["name"=> "Cape Coast", "country_id"=> "65"],
                ["name"=> "Obuasi", "country_id"=> "65"],
                ["name"=> "Teshie", "country_id"=> "65"],
                ["name"=> "Tema", "country_id"=> "65"],
                ["name"=> "Athens", "country_id"=> "66"],
                ["name"=> "Thessaloniki", "country_id"=> "66"],
                ["name"=> "Patras", "country_id"=> "66"],
                ["name"=> "Heraklion", "country_id"=> "66"],
                ["name"=> "Larissa", "country_id"=> "66"],
                ["name"=> "Volos", "country_id"=> "66"],
                ["name"=> "Rhodes", "country_id"=> "66"],
                ["name"=> "Ioannina", "country_id"=> "66"],
                ["name"=> "Chania", "country_id"=> "66"],
                ["name"=> "Chalcis", "country_id"=> "66"],
                ["name"=> "St. George's", "country_id"=> "67"],
                ["name"=> "Gouyave", "country_id"=> "67"],
                ["name"=> "Grenville", "country_id"=> "67"],
                ["name"=> "Victoria", "country_id"=> "67"],
                ["name"=> "Saint David's", "country_id"=> "67"],
                ["name"=> "Sauteurs", "country_id"=> "67"],
                ["name"=> "Hillsborough", "country_id"=> "67"],
                ["name"=> "Woburn", "country_id"=> "67"],
                ["name"=> "Grand Roy", "country_id"=> "67"],
                ["name"=> "Marquis", "country_id"=> "67"],
                ["name"=> "Guatemala City", "country_id"=> "68"],
                ["name"=> "Mixco", "country_id"=> "68"],
                ["name"=> "Villa Nueva", "country_id"=> "68"],
                ["name"=> "Quetzaltenango", "country_id"=> "68"],
                ["name"=> "Escuintla", "country_id"=> "68"],
                ["name"=> "Chinautla", "country_id"=> "68"],
                ["name"=> "Cobán", "country_id"=> "68"],
                ["name"=> "Chimaltenango", "country_id"=> "68"],
                ["name"=> "Huehuetenango", "country_id"=> "68"],
                ["name"=> "Jalapa", "country_id"=> "68"],
                ["name"=> "Conakry", "country_id"=> "69"],
                ["name"=> "Nzérékoré", "country_id"=> "69"],
                ["name"=> "Kankan", "country_id"=> "69"],
                ["name"=> "Kindia", "country_id"=> "69"],
                ["name"=> "Labé", "country_id"=> "69"],
                ["name"=> "Guéckédou", "country_id"=> "69"],
                ["name"=> "Kissidougou", "country_id"=> "69"],
                ["name"=> "Mamou", "country_id"=> "69"],
                ["name"=> "Siguiri", "country_id"=> "69"],
                ["name"=> "Boké", "country_id"=> "69"],
                ["name"=> "Bissau", "country_id"=> "70"],
                ["name"=> "Bafatá", "country_id"=> "70"],
                ["name"=> "Gabú", "country_id"=> "70"],
                ["name"=> "Bissora", "country_id"=> "70"],
                ["name"=> "Bolama", "country_id"=> "70"],
                ["name"=> "Cacheu", "country_id"=> "70"],
                ["name"=> "Bubaque", "country_id"=> "70"],
                ["name"=> "Catió", "country_id"=> "70"],
                ["name"=> "Mansôa", "country_id"=> "70"],
                ["name"=> "Buba", "country_id"=> "70"],
                ["name"=> "Georgetown", "country_id"=> "71"],
                ["name"=> "Linden", "country_id"=> "71"],
                ["name"=> "New Amsterdam", "country_id"=> "71"],
                ["name"=> "Anna Regina", "country_id"=> "71"],
                ["name"=> "Bartica", "country_id"=> "71"],
                ["name"=> "Skeldon", "country_id"=> "71"],
                ["name"=> "Rosignol", "country_id"=> "71"],
                ["name"=> "Mahaica", "country_id"=> "71"],
                ["name"=> "Vreed-en-Hoop", "country_id"=> "71"],
                ["name"=> "Parika", "country_id"=> "71"],
                ["name"=> "Port-au-Prince", "country_id"=> "72"],
                ["name"=> "Carrefour", "country_id"=> "72"],
                ["name"=> "Delmas", "country_id"=> "72"],
                ["name"=> "Cap-Haïtien", "country_id"=> "72"],
                ["name"=> "Pétionville", "country_id"=> "72"],
                ["name"=> "Gonaïves", "country_id"=> "72"],
                ["name"=> "Les Cayes", "country_id"=> "72"],
                ["name"=> "Jacmel", "country_id"=> "72"],
                ["name"=> "Port-de-Paix", "country_id"=> "72"],
                ["name"=> "Jérémie", "country_id"=> "72"],
                ["name"=> "Tegucigalpa", "country_id"=> "73"],
                ["name"=> "San Pedro Sula", "country_id"=> "73"],
                ["name"=> "Choloma", "country_id"=> "73"],
                ["name"=> "La Ceiba", "country_id"=> "73"],
                ["name"=> "El Progreso", "country_id"=> "73"],
                ["name"=> "Villanueva", "country_id"=> "73"],
                ["name"=> "Choluteca", "country_id"=> "73"],
                ["name"=> "Comayagua", "country_id"=> "73"],
                ["name"=> "Puerto Cortés", "country_id"=> "73"],
                ["name"=> "La Lima", "country_id"=> "73"],
                ["name"=> "Budapest", "country_id"=> "74"],
                ["name"=> "Debrecen", "country_id"=> "74"],
                ["name"=> "Szeged", "country_id"=> "74"],
                ["name"=> "Miskolc", "country_id"=> "74"],
                ["name"=> "Pécs", "country_id"=> "74"],
                ["name"=> "Győr", "country_id"=> "74"],
                ["name"=> "Nyíregyháza", "country_id"=> "74"],
                ["name"=> "Kecskemét", "country_id"=> "74"],
                ["name"=> "Székesfehérvár", "country_id"=> "74"],
                ["name"=> "Szombathely", "country_id"=> "74"],
                ["name"=> "Reykjavik", "country_id"=> "75"],
                ["name"=> "Kópavogur", "country_id"=> "75"],
                ["name"=> "Hafnarfjörður", "country_id"=> "75"],
                ["name"=> "Akureyri", "country_id"=> "75"],
                ["name"=> "Reykjanesbær", "country_id"=> "75"],
                ["name"=> "Garðabær", "country_id"=> "75"],
                ["name"=> "Mosfellsbær", "country_id"=> "75"],
                ["name"=> "Árborg", "country_id"=> "75"],
                ["name"=> "Akranes", "country_id"=> "75"],
                ["name"=> "Fjarðabyggð", "country_id"=> "75"],
                ["name"=> "Delhi", "country_id"=> "76"],
                ["name"=> "Mumbai", "country_id"=> "76"],
                ["name"=> "Bangalore", "country_id"=> "76"],
                ["name"=> "Kolkata", "country_id"=> "76"],
                ["name"=> "Chennai", "country_id"=> "76"],
                ["name"=> "Hyderabad", "country_id"=> "76"],
                ["name"=> "Pune", "country_id"=> "76"],
                ["name"=> "Ahmedabad", "country_id"=> "76"],
                ["name"=> "Jaipur", "country_id"=> "76"],
                ["name"=> "Surat", "country_id"=> "76"],
                ["name"=> "Jakarta", "country_id"=> "77"],
                ["name"=> "Surabaya", "country_id"=> "77"],
                ["name"=> "Bandung", "country_id"=> "77"],
                ["name"=> "Medan", "country_id"=> "77"],
                ["name"=> "Semarang", "country_id"=> "77"],
                ["name"=> "Makassar", "country_id"=> "77"],
                ["name"=> "Palembang", "country_id"=> "77"],
                ["name"=> "Tangerang", "country_id"=> "77"],
                ["name"=> "Depok", "country_id"=> "77"],
                ["name"=> "Bekasi", "country_id"=> "77"],
                ["name"=> "Tehran", "country_id"=> "78"],
                ["name"=> "Mashhad", "country_id"=> "78"],
                ["name"=> "Isfahan", "country_id"=> "78"],
                ["name"=> "Karaj", "country_id"=> "78"],
                ["name"=> "Shiraz", "country_id"=> "78"],
                ["name"=> "Tabriz", "country_id"=> "78"],
                ["name"=> "Qom", "country_id"=> "78"],
                ["name"=> "Ahvaz", "country_id"=> "78"],
                ["name"=> "Kermanshah", "country_id"=> "78"],
                ["name"=> "Urmia", "country_id"=> "78"],
                ["name"=> "Baghdad", "country_id"=> "79"],
                ["name"=> "Basra", "country_id"=> "79"],
                ["name"=> "Mosul", "country_id"=> "79"],
                ["name"=> "Erbil", "country_id"=> "79"],
                ["name"=> "Sulaymaniyah", "country_id"=> "79"],
                ["name"=> "Najaf", "country_id"=> "79"],
                ["name"=> "Karbala", "country_id"=> "79"],
                ["name"=> "Kirkuk", "country_id"=> "79"],
                ["name"=> "Hillah", "country_id"=> "79"],
                ["name"=> "Nasiriyah", "country_id"=> "79"],
                ["name"=> "Dublin", "country_id"=> "80"],
                ["name"=> "Cork", "country_id"=> "80"],
                ["name"=> "Limerick", "country_id"=> "80"],
                ["name"=> "Galway", "country_id"=> "80"],
                ["name"=> "Waterford", "country_id"=> "80"],
                ["name"=> "Drogheda", "country_id"=> "80"],
                ["name"=> "Dundalk", "country_id"=> "80"],
                ["name"=> "Swords", "country_id"=> "80"],
                ["name"=> "Bray", "country_id"=> "80"],
                ["name"=> "Navan", "country_id"=> "80"],
                ["name"=> "Jerusalem", "country_id"=> "81"],
                ["name"=> "Tel Aviv", "country_id"=> "81"],
                ["name"=> "Haifa", "country_id"=> "81"],
                ["name"=> "Rishon LeZion", "country_id"=> "81"],
                ["name"=> "Petah Tikva", "country_id"=> "81"],
                ["name"=> "Ashdod", "country_id"=> "81"],
                ["name"=> "Netanya", "country_id"=> "81"],
                ["name"=> "Beersheba", "country_id"=> "81"],
                ["name"=> "Holon", "country_id"=> "81"],
                ["name"=> "Bnei Brak", "country_id"=> "81"],
                ["name"=> "Rome", "country_id"=> "82"],
                ["name"=> "Milan", "country_id"=> "82"],
                ["name"=> "Naples", "country_id"=> "82"],
                ["name"=> "Turin", "country_id"=> "82"],
                ["name"=> "Palermo", "country_id"=> "82"],
                ["name"=> "Genoa", "country_id"=> "82"],
                ["name"=> "Bologna", "country_id"=> "82"],
                ["name"=> "Florence", "country_id"=> "82"],
                ["name"=> "Bari", "country_id"=> "82"],
                ["name"=> "Catania", "country_id"=> "82"],
                ["name"=> "Kingston", "country_id"=> "83"],
                ["name"=> "Spanish Town", "country_id"=> "83"],
                ["name"=> "Portmore", "country_id"=> "83"],
                ["name"=> "Montego Bay", "country_id"=> "83"],
                ["name"=> "May Pen", "country_id"=> "83"],
                ["name"=> "Mandeville", "country_id"=> "83"],
                ["name"=> "Old Harbour", "country_id"=> "83"],
                ["name"=> "Savanna-la-Mar", "country_id"=> "83"],
                ["name"=> "Ocho Rios", "country_id"=> "83"],
                ["name"=> "Port Antonio", "country_id"=> "83"],
                ["name"=> "Tokyo", "country_id"=> "84"],
                ["name"=> "Osaka", "country_id"=> "84"],
                ["name"=> "Nagoya", "country_id"=> "84"],
                ["name"=> "Sapporo", "country_id"=> "84"],
                ["name"=> "Fukuoka", "country_id"=> "84"],
                ["name"=> "Kobe", "country_id"=> "84"],
                ["name"=> "Kyoto", "country_id"=> "84"],
                ["name"=> "Yokohama", "country_id"=> "84"],
                ["name"=> "Kawasaki", "country_id"=> "84"],
                ["name"=> "Hiroshima", "country_id"=> "84"],
                ["name"=> "Amman", "country_id"=> "85"],
                ["name"=> "Zarqa", "country_id"=> "85"],
                ["name"=> "Irbid", "country_id"=> "85"],
                ["name"=> "Russeifa", "country_id"=> "85"],
                ["name"=> "Aqaba", "country_id"=> "85"],
                ["name"=> "Madaba", "country_id"=> "85"],
                ["name"=> "Jerash", "country_id"=> "85"],
                ["name"=> "Salt", "country_id"=> "85"],
                ["name"=> "Mafraq", "country_id"=> "85"],
                ["name"=> "Karak", "country_id"=> "85"],
                ["name"=> "Almaty", "country_id"=> "86"],
                ["name"=> "Nur-Sultan", "country_id"=> "86"],
                ["name"=> "Shymkent", "country_id"=> "86"],
                ["name"=> "Aktobe", "country_id"=> "86"],
                ["name"=> "Karaganda", "country_id"=> "86"],
                ["name"=> "Taraz", "country_id"=> "86"],
                ["name"=> "Pavlodar", "country_id"=> "86"],
                ["name"=> "Ust-Kamenogorsk", "country_id"=> "86"],
                ["name"=> "Semey", "country_id"=> "86"],
                ["name"=> "Atyrau", "country_id"=> "86"],
                ["name"=> "Nairobi", "country_id"=> "87"],
                ["name"=> "Mombasa", "country_id"=> "87"],
                ["name"=> "Kisumu", "country_id"=> "87"],
                ["name"=> "Nakuru", "country_id"=> "87"],
                ["name"=> "Eldoret", "country_id"=> "87"],
                ["name"=> "Ruiru", "country_id"=> "87"],
                ["name"=> "Kikuyu", "country_id"=> "87"],
                ["name"=> "Malindi", "country_id"=> "87"],
                ["name"=> "Thika", "country_id"=> "87"],
                ["name"=> "Kitale", "country_id"=> "87"],
                ["name"=> "Tarawa", "country_id"=> "88"],
                ["name"=> "Betio", "country_id"=> "88"],
                ["name"=> "Bikenibeu", "country_id"=> "88"],
                ["name"=> "Teaoraereke", "country_id"=> "88"],
                ["name"=> "Bairiki", "country_id"=> "88"],
                ["name"=> "Eita", "country_id"=> "88"],
                ["name"=> "Bonriki", "country_id"=> "88"],
                ["name"=> "Buota", "country_id"=> "88"],
                ["name"=> "Abaokoro", "country_id"=> "88"],
                ["name"=> "Banraeaba", "country_id"=> "88"],
                ["name"=> "Pyongyang", "country_id"=> "89"],
                ["name"=> "Hamhung", "country_id"=> "89"],
                ["name"=> "Chongjin", "country_id"=> "89"],
                ["name"=> "Nampo", "country_id"=> "89"],
                ["name"=> "Wonsan", "country_id"=> "89"],
                ["name"=> "Sinuiju", "country_id"=> "89"],
                ["name"=> "Sariwon", "country_id"=> "89"],
                ["name"=> "Kaesong", "country_id"=> "89"],
                ["name"=> "Haeju", "country_id"=> "89"],
                ["name"=> "Kanggye", "country_id"=> "89"],
                ["name"=> "Seoul", "country_id"=> "90"],
                ["name"=> "Busan", "country_id"=> "90"],
                ["name"=> "Incheon", "country_id"=> "90"],
                ["name"=> "Daegu", "country_id"=> "90"],
                ["name"=> "Daejeon", "country_id"=> "90"],
                ["name"=> "Gwangju", "country_id"=> "90"],
                ["name"=> "Suwon", "country_id"=> "90"],
                ["name"=> "Ulsan", "country_id"=> "90"],
                ["name"=> "Changwon", "country_id"=> "90"],
                ["name"=> "Goyang", "country_id"=> "90"],
                ["name"=> "Kuwait City", "country_id"=> "91"],
                ["name"=> "Hawalli", "country_id"=> "91"],
                ["name"=> "Salmiya", "country_id"=> "91"],
                ["name"=> "Sabah Al-Salem", "country_id"=> "91"],
                ["name"=> "Al Farwaniyah", "country_id"=> "91"],
                ["name"=> "Al Ahmadi", "country_id"=> "91"],
                ["name"=> "Jahra", "country_id"=> "91"],
                ["name"=> "Fahaheel", "country_id"=> "91"],
                ["name"=> "Mangaf", "country_id"=> "91"],
                ["name"=> "Khaitan", "country_id"=> "91"],
                ["name"=> "Bishkek", "country_id"=> "92"],
                ["name"=> "Osh", "country_id"=> "92"],
                ["name"=> "Jalal-Abad", "country_id"=> "92"],
                ["name"=> "Karakol", "country_id"=> "92"],
                ["name"=> "Tokmok", "country_id"=> "92"],
                ["name"=> "Uzgen", "country_id"=> "92"],
                ["name"=> "Balykchy", "country_id"=> "92"],
                ["name"=> "Kara-Balta", "country_id"=> "92"],
                ["name"=> "Naryn", "country_id"=> "92"],
                ["name"=> "Talas", "country_id"=> "92"],
                ["name"=> "Vientiane", "country_id"=> "93"],
                ["name"=> "Pakse", "country_id"=> "93"],
                ["name"=> "Savannakhet", "country_id"=> "93"],
                ["name"=> "Luang Prabang", "country_id"=> "93"],
                ["name"=> "Thakhek", "country_id"=> "93"],
                ["name"=> "Xam Neua", "country_id"=> "93"],
                ["name"=> "Phonsavan", "country_id"=> "93"],
                ["name"=> "Pakxan", "country_id"=> "93"],
                ["name"=> "Muang Xay", "country_id"=> "93"],
                ["name"=> "Attapeu", "country_id"=> "93"],
                ["name"=> "Riga", "country_id"=> "94"],
                ["name"=> "Daugavpils", "country_id"=> "94"],
                ["name"=> "Liepāja", "country_id"=> "94"],
                ["name"=> "Jelgava", "country_id"=> "94"],
                ["name"=> "Jūrmala", "country_id"=> "94"],
                ["name"=> "Ventspils", "country_id"=> "94"],
                ["name"=> "Rēzekne", "country_id"=> "94"],
                ["name"=> "Valmiera", "country_id"=> "94"],
                ["name"=> "Jēkabpils", "country_id"=> "94"],
                ["name"=> "Ogre", "country_id"=> "94"],
                ["name"=> "Beirut", "country_id"=> "95"],
                ["name"=> "Tripoli", "country_id"=> "95"],
                ["name"=> "Sidon", "country_id"=> "95"],
                ["name"=> "Tyre", "country_id"=> "95"],
                ["name"=> "Nabatieh", "country_id"=> "95"],
                ["name"=> "Jounieh", "country_id"=> "95"],
                ["name"=> "Zahle", "country_id"=> "95"],
                ["name"=> "Baalbek", "country_id"=> "95"],
                ["name"=> "Byblos", "country_id"=> "95"],
                ["name"=> "Batroun", "country_id"=> "95"],
                ["name"=> "Maseru", "country_id"=> "96"],
                ["name"=> "Teyateyaneng", "country_id"=> "96"],
                ["name"=> "Mafeteng", "country_id"=> "96"],
                ["name"=> "Hlotse", "country_id"=> "96"],
                ["name"=> "Mohale's Hoek", "country_id"=> "96"],
                ["name"=> "Maputsoe", "country_id"=> "96"],
                ["name"=> "Qacha's Nek", "country_id"=> "96"],
                ["name"=> "Quthing", "country_id"=> "96"],
                ["name"=> "Butha-Buthe", "country_id"=> "96"],
                ["name"=> "Mokhotlong", "country_id"=> "96"],
                ["name"=> "Monrovia", "country_id"=> "97"],
                ["name"=> "Gbarnga", "country_id"=> "97"],
                ["name"=> "Kakata", "country_id"=> "97"],
                ["name"=> "Bensonville", "country_id"=> "97"],
                ["name"=> "Harper", "country_id"=> "97"],
                ["name"=> "Voinjama", "country_id"=> "97"],
                ["name"=> "Buchanan", "country_id"=> "97"],
                ["name"=> "Zwedru", "country_id"=> "97"],
                ["name"=> "New Yekepa", "country_id"=> "97"],
                ["name"=> "Greenville", "country_id"=> "97"],
                ["name"=> "Tripoli", "country_id"=> "98"],
                ["name"=> "Benghazi", "country_id"=> "98"],
                ["name"=> "Misrata", "country_id"=> "98"],
                ["name"=> "Zawiya", "country_id"=> "98"],
                ["name"=> "Bayda", "country_id"=> "98"],
                ["name"=> "Tobruk", "country_id"=> "98"],
                ["name"=> "Ajdabiya", "country_id"=> "98"],
                ["name"=> "Sabha", "country_id"=> "98"],
                ["name"=> "Derna", "country_id"=> "98"],
                ["name"=> "Sirte", "country_id"=> "98"],
                ["name"=> "Vaduz", "country_id"=> "99"],
                ["name"=> "Schaan", "country_id"=> "99"],
                ["name"=> "Balzers", "country_id"=> "99"],
                ["name"=> "Triesen", "country_id"=> "99"],
                ["name"=> "Eschen", "country_id"=> "99"],
                ["name"=> "Mauren", "country_id"=> "99"],
                ["name"=> "Triesenberg", "country_id"=> "99"],
                ["name"=> "Ruggell", "country_id"=> "99"],
                ["name"=> "Gamprin", "country_id"=> "99"],
                ["name"=> "Schellenberg", "country_id"=> "99"],
                ["name"=> "Vilnius", "country_id"=> "100"],
                ["name"=> "Kaunas", "country_id"=> "100"],
                ["name"=> "Klaipėda", "country_id"=> "100"],
                ["name"=> "Šiauliai", "country_id"=> "100"],
                ["name"=> "Panevėžys", "country_id"=> "100"],
                ["name"=> "Alytus", "country_id"=> "100"],
                ["name"=> "Marijampolė", "country_id"=> "100"],
                ["name"=> "Mažeikiai", "country_id"=> "100"],
                ["name"=> "Jonava", "country_id"=> "100"],
                ["name"=> "Utena", "country_id"=> "100"],
                ["name"=> "Luxembourg City", "country_id"=> "101"],
                ["name"=> "Esch-sur-Alzette", "country_id"=> "101"],
                ["name"=> "Differdange", "country_id"=> "101"],
                ["name"=> "Dudelange", "country_id"=> "101"],
                ["name"=> "Ettelbruck", "country_id"=> "101"],
                ["name"=> "Diekirch", "country_id"=> "101"],
                ["name"=> "Wiltz", "country_id"=> "101"],
                ["name"=> "Echternach", "country_id"=> "101"],
                ["name"=> "Rumelange", "country_id"=> "101"],
                ["name"=> "Grevenmacher", "country_id"=> "101"],
                ["name"=> "Antananarivo", "country_id"=> "102"],
                ["name"=> "Toamasina", "country_id"=> "102"],
                ["name"=> "Antsirabe", "country_id"=> "102"],
                ["name"=> "Fianarantsoa", "country_id"=> "102"],
                ["name"=> "Mahajanga", "country_id"=> "102"],
                ["name"=> "Toliara", "country_id"=> "102"],
                ["name"=> "Antsiranana", "country_id"=> "102"],
                ["name"=> "Ambovombe", "country_id"=> "102"],
                ["name"=> "Amparafaravola", "country_id"=> "102"],
                ["name"=> "Nosy Be", "country_id"=> "102"],
                ["name"=> "Lilongwe", "country_id"=> "103"],
                ["name"=> "Blantyre", "country_id"=> "103"],
                ["name"=> "Mzuzu", "country_id"=> "103"],
                ["name"=> "Zomba", "country_id"=> "103"],
                ["name"=> "Mangochi", "country_id"=> "103"],
                ["name"=> "Kasungu", "country_id"=> "103"],
                ["name"=> "Karonga", "country_id"=> "103"],
                ["name"=> "Salima", "country_id"=> "103"],
                ["name"=> "Liwonde", "country_id"=> "103"],
                ["name"=> "Nkhotakota", "country_id"=> "103"],
                ["name"=> "Kuala Lumpur", "country_id"=> "104"],
                ["name"=> "George Town", "country_id"=> "104"],
                ["name"=> "Ipoh", "country_id"=> "104"],
                ["name"=> "Johor Bahru", "country_id"=> "104"],
                ["name"=> "Shah Alam", "country_id"=> "104"],
                ["name"=> "Kota Kinabalu", "country_id"=> "104"],
                ["name"=> "Kuching", "country_id"=> "104"],
                ["name"=> "Malacca City", "country_id"=> "104"],
                ["name"=> "Petaling Jaya", "country_id"=> "104"],
                ["name"=> "Seremban", "country_id"=> "104"],
                ["name"=> "Malé", "country_id"=> "105"],
                ["name"=> "Addu City", "country_id"=> "105"],
                ["name"=> "Fuvahmulah", "country_id"=> "105"],
                ["name"=> "Kulhudhuffushi", "country_id"=> "105"],
                ["name"=> "Thinadhoo", "country_id"=> "105"],
                ["name"=> "Naifaru", "country_id"=> "105"],
                ["name"=> "Eydhafushi", "country_id"=> "105"],
                ["name"=> "Dhidhdhoo", "country_id"=> "105"],
                ["name"=> "Mahibadhoo", "country_id"=> "105"],
                ["name"=> "Hulhumale", "country_id"=> "105"],
                ["name"=> "Bamako", "country_id"=> "106"],
                ["name"=> "Sikasso", "country_id"=> "106"],
                ["name"=> "Mopti", "country_id"=> "106"],
                ["name"=> "Koutiala", "country_id"=> "106"],
                ["name"=> "Kayes", "country_id"=> "106"],
                ["name"=> "Ségou", "country_id"=> "106"],
                ["name"=> "Gao", "country_id"=> "106"],
                ["name"=> "Kati", "country_id"=> "106"],
                ["name"=> "Timbuktu", "country_id"=> "106"],
                ["name"=> "Kidal", "country_id"=> "106"],
                ["name"=> "Valletta", "country_id"=> "107"],
                ["name"=> "Birkirkara", "country_id"=> "107"],
                ["name"=> "Mosta", "country_id"=> "107"],
                ["name"=> "St. Paul's Bay", "country_id"=> "107"],
                ["name"=> "Qormi", "country_id"=> "107"],
                ["name"=> "Sliema", "country_id"=> "107"],
                ["name"=> "Naxxar", "country_id"=> "107"],
                ["name"=> "Zabbar", "country_id"=> "107"],
                ["name"=> "Fgura", "country_id"=> "107"],
                ["name"=> "Żejtun", "country_id"=> "107"],
                ["name"=> "Majuro", "country_id"=> "108"],
                ["name"=> "Ebeye", "country_id"=> "108"],
                ["name"=> "Arno", "country_id"=> "108"],
                ["name"=> "Jabor", "country_id"=> "108"],
                ["name"=> "Wotje", "country_id"=> "108"],
                ["name"=> "Mili", "country_id"=> "108"],
                ["name"=> "Likiep", "country_id"=> "108"],
                ["name"=> "Kwajalein", "country_id"=> "108"],
                ["name"=> "Jaluit", "country_id"=> "108"],
                ["name"=> "Namu", "country_id"=> "108"],
                ["name"=> "Nouakchott", "country_id"=> "109"],
                ["name"=> "Nouadhibou", "country_id"=> "109"],
                ["name"=> "Kiffa", "country_id"=> "109"],
                ["name"=> "Rosso", "country_id"=> "109"],
                ["name"=> "Kaédi", "country_id"=> "109"],
                ["name"=> "Zouérat", "country_id"=> "109"],
                ["name"=> "Atar", "country_id"=> "109"],
                ["name"=> "Sélibaby", "country_id"=> "109"],
                ["name"=> "Aleg", "country_id"=> "109"],
                ["name"=> "Boutilimit", "country_id"=> "109"],
                ["name"=> "Port Louis", "country_id"=> "110"],
                ["name"=> "Beau Bassin-Rose Hill", "country_id"=> "110"],
                ["name"=> "Vacoas-Phoenix", "country_id"=> "110"],
                ["name"=> "Curepipe", "country_id"=> "110"],
                ["name"=> "Quatre Bornes", "country_id"=> "110"],
                ["name"=> "Triolet", "country_id"=> "110"],
                ["name"=> "Goodlands", "country_id"=> "110"],
                ["name"=> "Centre de Flacq", "country_id"=> "110"],
                ["name"=> "Mahebourg", "country_id"=> "110"],
                ["name"=> "Saint Pierre", "country_id"=> "110"],
                ["name"=> "Mexico City", "country_id"=> "111"],
                ["name"=> "Guadalajara", "country_id"=> "111"],
                ["name"=> "Monterrey", "country_id"=> "111"],
                ["name"=> "Puebla", "country_id"=> "111"],
                ["name"=> "Tijuana", "country_id"=> "111"],
                ["name"=> "León", "country_id"=> "111"],
                ["name"=> "Juárez", "country_id"=> "111"],
                ["name"=> "Zapopan", "country_id"=> "111"],
                ["name"=> "Mérida", "country_id"=> "111"],
                ["name"=> "Cancún", "country_id"=> "111"],
                ["name"=> "Palikir", "country_id"=> "112"],
                ["name"=> "Weno", "country_id"=> "112"],
                ["name"=> "Kolonia", "country_id"=> "112"],
                ["name"=> "Tofol", "country_id"=> "112"],
                ["name"=> "Lelu", "country_id"=> "112"],
                ["name"=> "Colonia", "country_id"=> "112"],
                ["name"=> "Sapwuahfik", "country_id"=> "112"],
                ["name"=> "Nukuoro", "country_id"=> "112"],
                ["name"=> "Fananu", "country_id"=> "112"],
                ["name"=> "Malem", "country_id"=> "112"],
                ["name"=> "Chișinău", "country_id"=> "113"],
                ["name"=> "Tiraspol", "country_id"=> "113"],
                ["name"=> "Bălți", "country_id"=> "113"],
                ["name"=> "Bender", "country_id"=> "113"],
                ["name"=> "Rîbnița", "country_id"=> "113"],
                ["name"=> "Cahul", "country_id"=> "113"],
                ["name"=> "Ungheni", "country_id"=> "113"],
                ["name"=> "Soroca", "country_id"=> "113"],
                ["name"=> "Orhei", "country_id"=> "113"],
                ["name"=> "Comrat", "country_id"=> "113"],
                ["name"=> "Monaco", "country_id"=> "114"],
                ["name"=> "Monte Carlo", "country_id"=> "114"],
                ["name"=> "La Condamine", "country_id"=> "114"],
                ["name"=> "Fontvieille", "country_id"=> "114"],
                ["name"=> "Moneghetti", "country_id"=> "114"],
                ["name"=> "Saint Roman", "country_id"=> "114"],
                ["name"=> "Larvotto", "country_id"=> "114"],
                ["name"=> "La Rousse", "country_id"=> "114"],
                ["name"=> "Saint Michel", "country_id"=> "114"],
                ["name"=> "Les Révoires", "country_id"=> "114"],
                ["name"=> "Ulaanbaatar", "country_id"=> "115"],
                ["name"=> "Erdenet", "country_id"=> "115"],
                ["name"=> "Darkhan", "country_id"=> "115"],
                ["name"=> "Choibalsan", "country_id"=> "115"],
                ["name"=> "Mörön", "country_id"=> "115"],
                ["name"=> "Khovd", "country_id"=> "115"],
                ["name"=> "Ölgii", "country_id"=> "115"],
                ["name"=> "Bayankhongor", "country_id"=> "115"],
                ["name"=> "Sükhbaatar", "country_id"=> "115"],
                ["name"=> "Arvaikheer", "country_id"=> "115"],
                ["name"=> "Podgorica", "country_id"=> "116"],
                ["name"=> "Nikšić", "country_id"=> "116"],
                ["name"=> "Pljevlja", "country_id"=> "116"],
                ["name"=> "Bijelo Polje", "country_id"=> "116"],
                ["name"=> "Cetinje", "country_id"=> "116"],
                ["name"=> "Bar", "country_id"=> "116"],
                ["name"=> "Herceg Novi", "country_id"=> "116"],
                ["name"=> "Berane", "country_id"=> "116"],
                ["name"=> "Budva", "country_id"=> "116"],
                ["name"=> "Ulcinj", "country_id"=> "116"],
                ["name"=> "Rabat", "country_id"=> "117"],
                ["name"=> "Casablanca", "country_id"=> "117"],
                ["name"=> "Fes", "country_id"=> "117"],
                ["name"=> "Marrakech", "country_id"=> "117"],
                ["name"=> "Tangier", "country_id"=> "117"],
                ["name"=> "Agadir", "country_id"=> "117"],
                ["name"=> "Meknes", "country_id"=> "117"],
                ["name"=> "Oujda", "country_id"=> "117"],
                ["name"=> "Kenitra", "country_id"=> "117"],
                ["name"=> "Tetouan", "country_id"=> "117"],
                ["name"=> "Maputo", "country_id"=> "118"],
                ["name"=> "Matola", "country_id"=> "118"],
                ["name"=> "Nampula", "country_id"=> "118"],
                ["name"=> "Beira", "country_id"=> "118"],
                ["name"=> "Chimoio", "country_id"=> "118"],
                ["name"=> "Quelimane", "country_id"=> "118"],
                ["name"=> "Tete", "country_id"=> "118"],
                ["name"=> "Nacala", "country_id"=> "118"],
                ["name"=> "Lichinga", "country_id"=> "118"],
                ["name"=> "Pemba", "country_id"=> "118"],
                ["name"=> "Yangon", "country_id"=> "119"],
                ["name"=> "Mandalay", "country_id"=> "119"],
                ["name"=> "Naypyidaw", "country_id"=> "119"],
                ["name"=> "Mawlamyine", "country_id"=> "119"],
                ["name"=> "Bago", "country_id"=> "119"],
                ["name"=> "Pathein", "country_id"=> "119"],
                ["name"=> "Monywa", "country_id"=> "119"],
                ["name"=> "Sittwe", "country_id"=> "119"],
                ["name"=> "Myitkyina", "country_id"=> "119"],
                ["name"=> "Taunggyi", "country_id"=> "119"],
                ["name"=> "Windhoek", "country_id"=> "120"],
                ["name"=> "Rundu", "country_id"=> "120"],
                ["name"=> "Walvis Bay", "country_id"=> "120"],
                ["name"=> "Oshakati", "country_id"=> "120"],
                ["name"=> "Swakopmund", "country_id"=> "120"],
                ["name"=> "Katima Mulilo", "country_id"=> "120"],
                ["name"=> "Grootfontein", "country_id"=> "120"],
                ["name"=> "Rehoboth", "country_id"=> "120"],
                ["name"=> "Otjiwarongo", "country_id"=> "120"],
                ["name"=> "Okahandja", "country_id"=> "120"],
                ["name"=> "Yaren", "country_id"=> "121"],
                ["name"=> "Denigomodu", "country_id"=> "121"],
                ["name"=> "Aiwo", "country_id"=> "121"],
                ["name"=> "Buada", "country_id"=> "121"],
                ["name"=> "Anabar", "country_id"=> "121"],
                ["name"=> "Anibare", "country_id"=> "121"],
                ["name"=> "Boe", "country_id"=> "121"],
                ["name"=> "Meneng", "country_id"=> "121"],
                ["name"=> "Ijuw", "country_id"=> "121"],
                ["name"=> "Uaboe", "country_id"=> "121"],
                ["name"=> "Kathmandu", "country_id"=> "122"],
                ["name"=> "Pokhara", "country_id"=> "122"],
                ["name"=> "Lalitpur", "country_id"=> "122"],
                ["name"=> "Bharatpur", "country_id"=> "122"],
                ["name"=> "Birgunj", "country_id"=> "122"],
                ["name"=> "Biratnagar", "country_id"=> "122"],
                ["name"=> "Dharan", "country_id"=> "122"],
                ["name"=> "Hetauda", "country_id"=> "122"],
                ["name"=> "Butwal", "country_id"=> "122"],
                ["name"=> "Janakpur", "country_id"=> "122"],
                ["name"=> "Amsterdam", "country_id"=> "123"],
                ["name"=> "Rotterdam", "country_id"=> "123"],
                ["name"=> "The Hague", "country_id"=> "123"],
                ["name"=> "Utrecht", "country_id"=> "123"],
                ["name"=> "Eindhoven", "country_id"=> "123"],
                ["name"=> "Tilburg", "country_id"=> "123"],
                ["name"=> "Groningen", "country_id"=> "123"],
                ["name"=> "Almere", "country_id"=> "123"],
                ["name"=> "Breda", "country_id"=> "123"],
                ["name"=> "Nijmegen", "country_id"=> "123"],
                ["name"=> "Auckland", "country_id"=> "124"],
                ["name"=> "Wellington", "country_id"=> "124"],
                ["name"=> "Christchurch", "country_id"=> "124"],
                ["name"=> "Hamilton", "country_id"=> "124"],
                ["name"=> "Tauranga", "country_id"=> "124"],
                ["name"=> "Napier-Hastings", "country_id"=> "124"],
                ["name"=> "Dunedin", "country_id"=> "124"],
                ["name"=> "Palmerston North", "country_id"=> "124"],
                ["name"=> "Nelson", "country_id"=> "124"],
                ["name"=> "Rotorua", "country_id"=> "124"]
            ];

            DB::table('cities')->insert($cities);
    }
}
